### ISSUE TITLE
Unable to build menu item on OpenELEC

### ISSUE THREAD

**Issue by ghost** [BigNoid/script.skinshortcuts#85]
Hi guys,

I know that a similar issue was already reported about this same issue on OpenELEC. But because the other one was close i decided to re-open a new one. 

The problem that I'm facing is that on OpenELEC i can not use a skin that is dependent on this module. I did some investigations and it seems that the code i trying to import a python module that is not available on OpenELEC. The faulty or missing module on OpenELEC is "unidecode". It seems that this module is not present on the python version running on OE. I'm using the latest stable OpenELEC running on the Raspberry Pi 2.

OpenELEC version is: 5.0.8
Python version is: Python 2.7.3 (default, Mar 31 2015, 15:16:49) [GCC 4.9.2] on linux2

The exception thrown in the Kodi logs is the following:
 Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named unidecode
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.skinshortcuts/default.py", line 35, in <module>
                                                import xmlfunctions, datafunctions, library, nodefunctions
                                              File "/storage/.kodi/addons/script.skinshortcuts/resources/lib/xmlfunctions.py", line 25, in <module>
                                                import datafunctions, template
                                              File "/storage/.kodi/addons/script.skinshortcuts/resources/lib/datafunctions.py", line 10, in <module>
                                                from unidecode import unidecode
                                            ImportError: No module named unidecode
                                            -->End of Python script error report<--

Regards

**Comment by ghost** [comment]
You manually installed Skin Shortcuts - if it's installed via "Install from zip" or along with a skin, the unidecode dependancy will be automatically installed from the Kodi repo. You can download the zip file here - http://mirrors.kodi.tv/addons/frodo/script.module.unidecode/ - and install it.

**Comment by ghost** [comment]
Ignoble61,

Thanks for the quick reply. You are completely right, the problem was resolved by removing the skin and the skinsshortcuts from Kodi and re-installing it. My skin no works without any issues. 

I think something went wrong with restoring my Pi.

Thanks.

Regards

P.S. I will close the issue.
